In [ ]:
import torch

SECTION A + B + C

In [ ]:
def alt_expand(a,b):
  #getting the shape of tensors A and B
  a_dims = a.shape
  b_dims = b.shape
  offset = len(b_dims) - len(a_dims)

  #making sure that tensor A is at least the size of tensor B
  #also im scaning the tensors from the last element of shape, if both tensors have different dimensions at the same location
  #and both diffrent than 1 then A can't be expanded and im returning an error
  assert len(a_dims) <= len(b_dims) , print('Dimensions of tensor A are greater then tensor B, cant expand')
  len_a, len_b = len(a_dims) - 1, len(b_dims) - 1
  for i in range(len(a_dims)):
    if ((a_dims[len_a]) != (b_dims[len_b])):
      if((a_dims[len_a]) != 1) and ((b_dims[len_b]) != 1):
        print(f'Cant expand')
        return False
    len_a -= 1
    len_b -= 1
  #cloning tensor A into ret_t (the tensor im returning)
  ret_t = torch.clone(a)
  #compering the dimensions of tensor A to the dimensions of thensor B, if dimensions of A are smaller then B we expand 
  #the dimensions of A to the dimensions of B
  for i in range(len(a.shape)):
    if a_dims[i] == b_dims[offset+i]: continue
    lst = [ret_t] * b_dims[offset+i]
    ret_t = torch.stack(lst, i+1)
    ret_t = torch.squeeze(ret_t,i)
  #here we expanding the size of tensor A to the size of tensor B
  for i in reversed(range(offset)):
      lst = [ret_t] * b_dims[i]
      ret_t = torch.stack(lst, 0)


  print(f'tensor a:\n{a}', f'tensor b:\n{b}', sep='\n\n')
  print('\n')
  return ret_t


SECTION B

In [ ]:
def is_brod(a,b):
  #getting the shape of tensors A and B
  a_dims = a.shape
  b_dims = b.shape
  #making sure that tensor A is at leat the size of tensor B
  #also im scaning the tensors from the last element of shape, if both tensors have different dimensions at the same location
  #and both diffrent than 1 then A can't be expanded and im returning an error
  assert len(a_dims) <= len(b_dims) , print('Dimensions of tensor A are greater then tensor B, cant expand')
  len_a, len_b = len(a_dims) - 1, len(b_dims) - 1
  for i in range(len(a_dims)):
    if ((a_dims[len_a]) != (b_dims[len_b])):
      if((a_dims[len_a]) != 1) and ((b_dims[len_b]) != 1):
        return False
    len_a -= 1
    len_b -= 1
  return True

SECTION C

In [ ]:
def alt_brod_tensors(a,b):

  #checking if tensors a and be can be broadcasted
  ok_for_broad = is_brod(a,b)
  if not ok_for_broad:
    print('Cant broadcast this tensors')

  #the size to wichw the tensors wil be broadcasted
  new_size = list()

  #order the tensors in ascending order by number of dimensions
  if len(a.shape) <= len(b.shape):
    up_a, up_b = a, b
  else:
    up_a, up_b = b, a
  shape_a, shape_b = up_a.shape, up_b.shape

  #adding degenerate dimensions to a
  l = len(shape_b) - len(shape_a)
  for i in range(l):
    a = torch.unsqueeze(a, 0)
    shape_a = a.shape

  for i in range(len(shape_a)):
    if shape_a[i] >= shape_b[i]:
      size_dim = shape_a[i]
    else:
      size_dim = shape_b[i]
    new_size.append(size_dim)
    
  #add the current dimension and its size to our list.
  print(f'this is new_size: {new_size})')
  empty_tr = torch.empty(new_size)
  ret1, ret2 = alt_expand(a,empty_tr), alt_expand(b, empty_tr)


  return ret1, ret2 

SECTION D

In [ ]:
a = torch.rand(2,1,3)
b = torch.rand(4,1,2,1,3)

In [ ]:
my_res = alt_expand(a,b)

tensor a:
tensor([[[0.5953, 0.7305, 0.6995]],

        [[0.3436, 0.5737, 0.0349]]])

tensor b:
tensor([[[[[0.4503, 0.7900, 0.3997]],

          [[0.0092, 0.4480, 0.7698]]]],



        [[[[0.7214, 0.4173, 0.6268]],

          [[0.6724, 0.2568, 0.9142]]]],



        [[[[0.8481, 0.7549, 0.2262]],

          [[0.1585, 0.4920, 0.1334]]]],



        [[[[0.0735, 0.6655, 0.2987]],

          [[0.7496, 0.8272, 0.9128]]]]])




In [ ]:
pytorch_res = a.expand_as(b)

In [ ]:
res = torch.equal(my_res, pytorch_res)
print(res)

True


In [ ]:
c = torch.rand(3,1)
d = torch.rand(2,1,3)

In [ ]:
my1, my2 = alt_brod_tensors(c, d)

this is new_size: [2, 3, 3])
tensor a:
tensor([[[0.6596],
         [0.1479],
         [0.3508]]])

tensor b:
tensor([[[4.5232e-37, 3.0810e-41, 7.0065e-44],
         [7.0065e-44, 6.3058e-44, 6.7262e-44],
         [7.2868e-44, 6.3058e-44, 6.7262e-44]],

        [[7.7071e-44, 1.1771e-43, 7.0065e-44],
         [6.7262e-44, 8.1275e-44, 6.8664e-44],
         [7.8473e-44, 8.1275e-44, 7.1466e-44]]])


tensor a:
tensor([[[0.6294, 0.2331, 0.2753]],

        [[0.1124, 0.3638, 0.6859]]])

tensor b:
tensor([[[4.5232e-37, 3.0810e-41, 7.0065e-44],
         [7.0065e-44, 6.3058e-44, 6.7262e-44],
         [7.2868e-44, 6.3058e-44, 6.7262e-44]],

        [[7.7071e-44, 1.1771e-43, 7.0065e-44],
         [6.7262e-44, 8.1275e-44, 6.8664e-44],
         [7.8473e-44, 8.1275e-44, 7.1466e-44]]])




In [ ]:
pt1, pt2 = torch.broadcast_tensors(c, d)

In [ ]:
res = torch.equal(my1, pt1) and torch.equal(my2, pt2)

In [ ]:
print(res)

True
